/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poslaundry.UI;

import db.Db;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mount
 */
public class ProductsByQty extends javax.swing.JInternalFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public ProductsByQty() throws Exception {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        conn = Db.java_db();
        PremiumtableUpdate();
        premium_category();
      
    }
    
    public class CategoryItem{
        int id;
        String name;
        
        public CategoryItem(int id, String name){
            this.id = id;
            this.name = name;
        }
        
        @Override
        public String toString(){
            return name;
        }
    }
     private void premium_category(){
        try {
            pst = conn.prepareStatement("select * from category");
            rs = pst.executeQuery();
            cmbpremiumcat.removeAllItems();
            while(rs.next()){
                cmbpremiumcat.addItem(new CategoryItem(rs.getInt(1), rs.getString(2)));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(ProductsByQty.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    
     
     
   
    private void PremiumtableUpdate(){
        try{
//             select * from p.id, p.product,c.cat_id, p.price, p.qty, p.barcode,p.status from premium p, category c where p.cat_id = c.id
        String sql ="select * from premium";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        premiumTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
//    JOptionPane.showMessageDialog(null, e);
    }
    finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }}

    
   
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtpremiumproduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbpremiumcat = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtpremiumPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpremiumQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpremiumbarcode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGeneralweight1 = new javax.swing.JTextField();
        btnpremiumAdd = new javax.swing.JButton();
        btnpremiumUpdate = new javax.swing.JButton();
        btnpremiumdelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        premiumTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        btnpremiumdelete1 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        txtSearcjh = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 673, 676, 4));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 0, 656));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Premium");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 51), new java.awt.Color(102, 255, 255), java.awt.Color.black, java.awt.Color.orange), "Laundry Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 0, 18))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel7.setText("Product");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel8.setText("Category");

        cmbpremiumcat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel9.setText("Price");

        txtpremiumPrice.setText("0");
        txtpremiumPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpremiumPriceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel10.setText("Qty");

        txtpremiumQty.setText("0");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel11.setText("Product Code");

        txtpremiumbarcode.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel14.setText("Weight/KG");

        txtGeneralweight1.setText("0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeneralweight1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtpremiumbarcode)
                        .addComponent(txtpremiumQty, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtpremiumPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbpremiumcat, javax.swing.GroupLayout.Alignment.LEADING, 0, 162, Short.MAX_VALUE)
                        .addComponent(txtpremiumproduct, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpremiumproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbpremiumcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpremiumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtpremiumQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtGeneralweight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtpremiumbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        btnpremiumAdd.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnpremiumAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnpremiumAdd.setText("Add");
        btnpremiumAdd.setMaximumSize(new java.awt.Dimension(85, 39));
        btnpremiumAdd.setMinimumSize(new java.awt.Dimension(85, 39));
        btnpremiumAdd.setOpaque(false);
        btnpremiumAdd.setPreferredSize(new java.awt.Dimension(85, 39));
        btnpremiumAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremiumAddActionPerformed(evt);
            }
        });

        btnpremiumUpdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnpremiumUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnpremiumUpdate.setText("Update");
        btnpremiumUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremiumUpdateActionPerformed(evt);
            }
        });

        btnpremiumdelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnpremiumdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnpremiumdelete.setText("Delete");
        btnpremiumdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremiumdeleteActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.pink, java.awt.Color.red, java.awt.Color.black, java.awt.Color.orange));

        premiumTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.pink, java.awt.Color.red, java.awt.Color.black, java.awt.Color.orange));
        premiumTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        premiumTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premiumTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(premiumTable);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 51, 51), new java.awt.Color(102, 255, 255), java.awt.Color.black, java.awt.Color.orange), "Customer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 0, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel13.setText("CID");

        CID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CIDKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel15.setText("Customer Name");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel16.setText("Address");

        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel17.setText("Phone/Mobile");

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnpremiumdelete1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnpremiumdelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnpremiumdelete1.setText("Reset");
        btnpremiumdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremiumdelete1ActionPerformed(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));

        txtSearcjh.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        txtSearcjh.setBorder(null);
        txtSearcjh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearcjhActionPerformed(evt);
            }
        });
        txtSearcjh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearcjhKeyReleased(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Search By Customer ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator12)
                                            .addComponent(txtSearcjh, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(73, 73, 73))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnpremiumAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpremiumUpdate)
                                .addGap(14, 14, 14)
                                .addComponent(btnpremiumdelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpremiumdelete1)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel18))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearcjh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpremiumAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpremiumUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpremiumdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpremiumdelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpremiumAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremiumAddActionPerformed
                 int refs;
            refs = 1325 + (int) (Math.random()*4238);
            //int ref = (refs);
            String str1 = Integer.toString(refs); 
             txtpremiumbarcode.setText(str1);
        try {
            String product = txtpremiumproduct.getText();
            CategoryItem item = (CategoryItem)cmbpremiumcat.getSelectedItem();
//            String cate = cmbpremiumcat.getSelectedItem().toString();
//            String status = cmbpremiumStatus.getSelectedItem().toString();
            String price = txtpremiumPrice.getText();
            String qty = txtpremiumQty.getText();
             String weight = txtGeneralweight1.getText();
            String barcode = txtpremiumbarcode.getText();
            
            String cid = CID.getText();
            String name = cname.getText();
            String Address = address.getText();
            String Phone = phone.getText();

            pst = conn.prepareStatement("insert into premium (product, category, price, qty,weight, product_code, CID,Customer_Name,Address,Phone) values (?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, product);
            pst.setString(2, item.name);
            pst.setString(3, price);
            pst.setString(4, qty);
             pst.setString(5, weight);
            pst.setString(6, barcode);
            
             pst.setString(7, cid);
              pst.setString(8, name);
               pst.setString(9, Address);
                pst.setString(10, Phone);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Hooray! Product Added");
            txtpremiumproduct.setText(null);
            txtpremiumPrice.setText("0");
            txtpremiumQty.setText("0");
            txtpremiumbarcode.setText(null);
            
            CID.setText(null);
            cname.setText(null);
            address.setText(null);
            txtGeneralweight1.setText("0.0");
            txtpremiumbarcode.setText(null);
            phone.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(ProductsByQty.class.getName()).log(Level.SEVERE, null, ex);
        }
        PremiumtableUpdate();
        updateUI();
    }//GEN-LAST:event_btnpremiumAddActionPerformed

    private void btnpremiumUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremiumUpdateActionPerformed
        try {
            DefaultTableModel d1 = (DefaultTableModel) premiumTable.getModel();

            int selectIndex = premiumTable.getSelectedRow();
            int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

            String product = txtpremiumproduct.getText();
             CategoryItem item = (CategoryItem)cmbpremiumcat.getSelectedItem();
            String price = txtpremiumPrice.getText();
            String qty = txtpremiumQty.getText();
            String barcode = txtpremiumbarcode.getText();
            

            pst = conn.prepareStatement("update premium set product=?, cat_id=?,price=?, qty=?, barcode=? where id=?");
            pst.setString(1, product);
            pst.setInt(2, item.id);
            pst.setString(3, price);
            pst.setString(4, qty);
            pst.setString(5, barcode);
           
            pst.setInt(6, id);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Hooray! product updated");

        } catch (SQLException ex) {
            Logger.getLogger(ProductsByQty.class.getName()).log(Level.SEVERE, null, ex);
        }
        PremiumtableUpdate();
         txtpremiumproduct.setText(null);
            txtpremiumPrice.setText("0");
            txtpremiumQty.setText("0");
            txtpremiumbarcode.setText(null);
            
            CID.setText(null);
            cname.setText(null);
            address.setText(null);
            txtGeneralweight1.setText("0.0");
            txtpremiumbarcode.setText(null);
            phone.setText(null);
        
        cmbpremiumcat.setSelectedIndex(-1);
        txtpremiumproduct.requestFocus();
    }//GEN-LAST:event_btnpremiumUpdateActionPerformed

    private void premiumTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premiumTableMouseClicked
        DefaultTableModel d1 = (DefaultTableModel) premiumTable.getModel();

        int selectIndex = premiumTable.getSelectedRow();
        txtpremiumproduct.setText(d1.getValueAt(selectIndex, 1).toString());
        cmbpremiumcat.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
         txtpremiumPrice.setText(d1.getValueAt(selectIndex, 3).toString());
          txtpremiumQty.setText(d1.getValueAt(selectIndex, 4).toString());
          txtGeneralweight1.setText(d1.getValueAt(selectIndex, 5).toString());
           txtpremiumbarcode.setText(d1.getValueAt(selectIndex, 6).toString());
           
           CID.setText(d1.getValueAt(selectIndex, 7).toString());
           cname.setText(d1.getValueAt(selectIndex, 8).toString());
           address.setText(d1.getValueAt(selectIndex, 9).toString());
           phone.setText(d1.getValueAt(selectIndex, 10).toString());
         

    }//GEN-LAST:event_premiumTableMouseClicked

    private void btnpremiumdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremiumdeleteActionPerformed
       DefaultTableModel d1 = (DefaultTableModel) premiumTable.getModel();

        int selectIndex = premiumTable.getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the Record","warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            try {
                pst = conn.prepareStatement("delete from premium where id=?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Hooray! Product Deleted");
                PremiumtableUpdate();
                 txtpremiumproduct.setText(null);
            txtpremiumPrice.setText("0");
            txtpremiumQty.setText("0");
            txtpremiumbarcode.setText(null);
            
            CID.setText(null);
            cname.setText(null);
            address.setText(null);
            txtGeneralweight1.setText("0.0");
            txtpremiumbarcode.setText(null);
            phone.setText(null);
                cmbpremiumcat.setSelectedIndex(-1);
                txtpremiumproduct.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(items.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        updateUI();
    }//GEN-LAST:event_btnpremiumdeleteActionPerformed

    private void CIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CIDKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String name = CID.getText();
            try {
                pst = conn.prepareStatement("select * from customer where CID=?");
                
                pst.setString(1, name);
                rs = pst.executeQuery();
                
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "CID not Found");
                }else{
                    String Name = rs.getString("Name");
                    String Addr = rs.getString("Address");
                    String Phone = rs.getString("Phone");
                   
                    
                    cname.setText(Name.trim());
                    address.setText(Addr.trim());
                    phone.setText(Phone.trim());
                    cmbpremiumcat.setSelectedIndex(-1);
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_CIDKeyReleased

    private void btnpremiumdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremiumdelete1ActionPerformed
        txtpremiumproduct.setText(null);
            txtpremiumPrice.setText("0");
            txtpremiumQty.setText("0");
            txtpremiumbarcode.setText(null);
            
            CID.setText(null);
            cname.setText(null);
            address.setText(null);
            txtGeneralweight1.setText("0.0");
            txtpremiumbarcode.setText(null);
            phone.setText(null);
            
           
            
           
    }//GEN-LAST:event_btnpremiumdelete1ActionPerformed

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String name = cname.getText();
            try {
                pst = conn.prepareStatement("select * from customer where Name=?");
                
                pst.setString(1, name);
                rs = pst.executeQuery();
                
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "Name not Found");
                }else{
                    String Name = rs.getString("CID");
                    String Addr = rs.getString("Address");
                    String Phone = rs.getString("Phone");
                   
                    
                    CID.setText(Name.trim());
                    address.setText(Addr.trim());
                    phone.setText(Phone.trim());
                    
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_cnameKeyReleased

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
       
    }//GEN-LAST:event_addressKeyReleased

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String name = phone.getText();
            try {
                pst = conn.prepareStatement("select * from customer where Phone=?");
                
                pst.setString(1, name);
                rs = pst.executeQuery();
                
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "Phone not Found");
                }else{
                    String Name = rs.getString("CID");
                    String Addr = rs.getString("Name");
                    String Phone = rs.getString("Address");
                   
                    
                    CID.setText(Name.trim());
                    cname.setText(Addr.trim());
                    address.setText(Phone.trim());
                    
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_phoneKeyReleased

    private void txtSearcjhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearcjhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearcjhActionPerformed
    private void tableUpdate(){
     
        String category = txtSearcjh.getText();
        if(txtSearcjh.getText().length() >0){
        
        try {
            String table = "SELECT  *  FROM `premium` where CID LIKE  '%"+category+"%' ";
            pst = conn.prepareStatement(table);
            rs = pst.executeQuery();
            premiumTable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(coynt.class.getName()).log(Level.SEVERE, null, ex);
            {
            }
            }
        }else{
        }    
        
    }
    private void txtSearcjhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearcjhKeyReleased
        tableUpdate();

    }//GEN-LAST:event_txtSearcjhKeyReleased

    private void txtpremiumPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpremiumPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpremiumPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CID;
    private javax.swing.JTextField address;
    private javax.swing.JButton btnpremiumAdd;
    private javax.swing.JButton btnpremiumUpdate;
    private javax.swing.JButton btnpremiumdelete;
    private javax.swing.JButton btnpremiumdelete1;
    private javax.swing.JComboBox cmbpremiumcat;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField phone;
    private javax.swing.JTable premiumTable;
    private javax.swing.JTextField txtGeneralweight1;
    private javax.swing.JTextField txtSearcjh;
    private javax.swing.JTextField txtpremiumPrice;
    private javax.swing.JTextField txtpremiumQty;
    private javax.swing.JTextField txtpremiumbarcode;
    private javax.swing.JTextField txtpremiumproduct;
    // End of variables declaration//GEN-END:variables
}
